package commands

import "fmt"

func PrintUsage() {
	fmt.Println("Shipyard CLI (Client Mode)")
	fmt.Println("Usage: shipyard-cli [global flags] <command> [command flags]")
	fmt.Println("\nGlobal Flags:")
	fmt.Println("  --config <path>   Config file path (default: shipyard.toml)")
	fmt.Println("  --server <url>    Shipyard Server URL")
	fmt.Println("\nCommands:")
	fmt.Println("  login             Login to Shipyard Server")
	fmt.Println("  logout            Logout")
	fmt.Println("  deploy            Deploy application")
	fmt.Println("  launch            Initialize and deploy a new application")
	fmt.Println("  status            Show status of current project application")
	fmt.Println("  vars              Manage application environment variables (list, set, unset)")
	fmt.Println("  logs              View application instance logs")
	fmt.Println("  app               App management commands (restart, stop, status)")
	fmt.Println("  build             Build artifact management commands (list)")
	fmt.Println("  domain            Domain management commands (check)")
	fmt.Println("  version           Show version")
	fmt.Println("  help              Show help")
	fmt.Println("\n--- Variable Management (vars) ---")
	fmt.Println("  vars list [--app <name>]")
	fmt.Println("      List application environment variable keys")
	fmt.Println("  vars set KEY=VALUE [--app <name>]")
	fmt.Println("      Set environment variable")
	fmt.Println("  vars unset KEY [--app <name>]")
	fmt.Println("      Delete environment variable")
	fmt.Println("\n--- Log Viewing (logs) ---")
	fmt.Println("  logs [app-name] [--host <host>] [--port <port>] [--lines N] [-f|--follow]")
	fmt.Println("      View application instance logs")
	fmt.Println("      Options:")
	fmt.Println("        --port <port>      View logs for specific port")
	fmt.Println("        --lines <N>        Show last N lines (default 500)")
	fmt.Println("        --follow, -f       Follow log output")
	fmt.Println("        --color            Enable color output (default enabled)")
	fmt.Println("        --no-color         Disable color output")
	fmt.Println("\n--- App Management (app) ---")
	fmt.Println("  app restart [--app <name>] [--host <host>]")
	fmt.Println("      Restart application")
	fmt.Println("  app stop [--app <name>] [--host <host>]")
	fmt.Println("      Stop application")
	fmt.Println("  app status [--app <name>] [--host <host>]")
	fmt.Println("      View application status")
	fmt.Println("\n--- Build Management (build) ---")
	fmt.Println("  build list [--app <name>]")
	fmt.Println("      List build artifacts for an application")
	fmt.Println("\n--- Domain Management (domain) ---")
	fmt.Println("  domain check [--app <name>] [--host <host>]")
	fmt.Println("      Check Caddy configuration")
}
